### ISSUE TITLE
What does speed mean exactly?

### ISSUE THREAD

**Issue by nickpleis** [kitesurfer1404/WS2812FX#113]
It's unclear to me what I'm actually setting when I set the speed. Can I get some guidance on how to use it as I get wildly different results depending on the length of the strip.

Awesome library btw!

**Comment by moose4lord** [comment]
The speed parameter can through people off. Maybe counter-intuitively, small speed values give fast animations, while large values give slower animations, so that can be a point of confusion. Let me try to clear things up.

The speed setting can have two meanings depending on if the effect has a repeating pattern or not. Effects like Comet and Theater Chase have a definite, repeating pattern which cycles over and over again. Other effects, like Fireworks and Single Dynamic, have a more random nature.

For effects that cycle, speed is the time (in milliseconds) it takes to perform one cycle of animation. So if you set speed to 10000 and run the Comet effect, it'll take 10 seconds for the comet to travel from the beginning of the strip to the end. WS2812FX factors in the length of the LED strip, so it doesn't matter how long the strip is, it'll take 10 seconds if the strip has 30 LEDs or 300 LEDs. For these types of effects speed tends to be a large number, say from 1000 to 10000. I have a long strip of 300 LEDs on the front of my house, and for that many LEDs, speed values in the 20000 to 50000 range are not uncommon.

For effects that are more random, speed is simply the delay (again in milliseconds) from one "frame" of animation to the next. So for the Fireworks effect, setting speed to 50 means the LED strip will be updated every 50 milliseconds. For these effects speed tends to be a small number, say from 20 to 200.

So finding the right speed value depends on the effect, the length of the strip and the mood you're trying to create. It can take a little experimentation to get it right.

Hope that helps.
