### ISSUE TITLE
GRBW issue on white led not working

### ISSUE THREAD

**Issue by sarus3749** [kitesurfer1404/WS2812FX#267]
Hello.
I looked for it in the other topics but I'm not sure it was solved.

I've a SK6812 RGBW from BFT Lighting which is working well. I setted up the LED model on GRBW and everything is working (all my 60 leds on a 1m strip and all the effects) but the white leds.
RGB are lighting but the white one is still off.

I don't know if there is a specific way to send it with the web interface, I tried "rgb(255,255,255)" but still not working.
Am I doing it wrong or is there a bug ?

Thank you for your answer

**Comment by moose4lord** [comment]
The only preset color for RGBW LEDs is **ULTRAWHITE**.

Try the _ws2812fx_segments_ example sketch with this:
```c++
ws2812fx.setSegment(0,  0,  LED_COUNT-1, FX_MODE_STATIC, ULTRAWHITE, 1000, false);
```
That should at least show you that your white LEDs are working.

Beyond that, the web interface sketches in the **examples** folder do not support RGBW LEDs, because the HTML color picker doesn't support a separate white channel. You would have to write your own.
