### ISSUE TITLE
Divide by zero in mode_breath?

### ISSUE THREAD

**Issue by debsahu** [kitesurfer1404/WS2812FX#94]
https://github.com/toblum/McLighting/issues/166 pointed out that if brightness is zero, mode_breath crashes. I'm guessing maybe we got to check divide by zero
https://github.com/kitesurfer1404/WS2812FX/blob/6ce37240ec411b24baa0444597bb88d828555569/src/WS2812FX.cpp#L555-L558

I prosopse:
```
uint8_t r, g, b, w;
if(_brightness) {
  w = (SEGMENT.colors[0] >> 24 & 0xFF) * lum / _brightness; // modify RGBW colors with brightness info 
  r = (SEGMENT.colors[0] >> 16 & 0xFF) * lum / _brightness; 
  g = (SEGMENT.colors[0] >>  8 & 0xFF) * lum / _brightness; 
  b = (SEGMENT.colors[0]       & 0xFF) * lum / _brightness; 
} else {
  w = 0; r = 0; g = 0; b = 0;
}
```

**Comment by flagstone78** [comment]
mode_fade() does the same thing on line 576 to 579.

**Comment by moose4lord** [comment]
Thanks for catching this. I've never been happy with the breath or fade modes. Breath doesn't work the way it's supposed to, since it tries to set the frame delay less the MIN_SPEED. And both breath and fade incorrectly apply the brightness setting twice, once in the WS2812FX code and again in the Adafruit_NeoPixel setPixelColor() function. They both look OK, but the implementation is flawed. I'll have to go back and look at those.

**Comment by debsahu** [comment]
Closing, thank you.
